"""Architecture, database schema, API, and UI layout domain models.

Generated by the System Architect and Database Architect agents during
the Development Civilization workflow (Component 4).
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# ── Architecture Patterns ───────────────────────────────────────────────

class ArchitecturePattern(str, Enum):
    MONOLITH = "monolith"
    MICROSERVICES = "microservices"
    EVENT_DRIVEN = "event_driven"
    LAYERED = "layered"
    HEXAGONAL = "hexagonal"
    CQRS = "cqrs"
    EVENT_SOURCING = "event_sourcing"
    SERVERLESS = "serverless"
    SOA = "service_oriented"
    MESH = "service_mesh"


class CommunicationProtocol(str, Enum):
    REST = "rest"
    GRPC = "grpc"
    GRAPHQL = "graphql"
    WEBSOCKET = "websocket"
    MESSAGE_QUEUE = "message_queue"
    EVENT_STREAM = "event_stream"


class DeploymentStrategy(str, Enum):
    BLUE_GREEN = "blue_green"
    CANARY = "canary"
    ROLLING = "rolling"
    RECREATE = "recreate"
    ROLLBACK = "rollback"


# ── Service Definitions ─────────────────────────────────────────────────

class ServiceDefinition(BaseModel):
    """A microservice or module in the architecture."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = ""
    description: str = ""
    language: str = "python"
    framework: str = "fastapi"
    port: int = 8000
    replicas: int = 2
    dependencies: list[str] = Field(default_factory=list)
    environment_variables: dict[str, str] = Field(default_factory=dict)
    resource_limits: dict[str, str] = Field(
        default_factory=lambda: {"cpu": "500m", "memory": "512Mi"}
    )
    health_check_path: str = "/health"
    api_prefix: str = "/api/v1"
    protocols: list[CommunicationProtocol] = Field(default=[CommunicationProtocol.REST])
    owns_database: bool = True
    is_internal: bool = False
    metadata: dict[str, Any] = Field(default_factory=dict)


# ── Database Schema Definitions ─────────────────────────────────────────

class ColumnType(str, Enum):
    UUID = "uuid"
    STRING = "string"
    TEXT = "text"
    INTEGER = "integer"
    BIGINT = "bigint"
    FLOAT = "float"
    DECIMAL = "decimal"
    BOOLEAN = "boolean"
    DATE = "date"
    DATETIME = "datetime"
    TIMESTAMP = "timestamp"
    JSON = "json"
    JSONB = "jsonb"
    ARRAY = "array"
    ENUM = "enum"
    RELATIONSHIP = "relationship"


class ColumnConstraint(str, Enum):
    PRIMARY_KEY = "primary_key"
    FOREIGN_KEY = "foreign_key"
    UNIQUE = "unique"
    NOT_NULL = "not_null"
    CHECK = "check"
    INDEX = "index"
    DEFAULT = "default"


class ColumnDefinition(BaseModel):
    """A single column/field in a database table."""

    name: str = ""
    column_type: ColumnType = ColumnType.STRING
    nullable: bool = False
    default: Any = None
    is_primary_key: bool = False
    is_unique: bool = False
    is_indexed: bool = False
    foreign_key: str | None = None  # "table.column" format
    constraints: list[ColumnConstraint] = Field(default_factory=list)
    description: str = ""
    max_length: int | None = None
    precision: int | None = None
    scale: int | None = None
    enum_values: list[str] | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class TableDefinition(BaseModel):
    """A database table/collection definition."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = ""
    schema_name: str = "public"
    columns: list[ColumnDefinition] = Field(default_factory=list)
    indexes: list[dict[str, Any]] = Field(default_factory=list)
    partition_key: str | None = None
    estimated_row_count: int = 1000
    description: str = ""
    timestamps: bool = True  # add created_at, updated_at
    soft_delete: bool = False
    metadata: dict[str, Any] = Field(default_factory=dict)


class DatabaseSchema(BaseModel):
    """Complete database schema for a project."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = ""
    database_type: str = "postgresql"
    tables: list[TableDefinition] = Field(default_factory=list)
    relationships: list[dict[str, str]] = Field(default_factory=list)
    migrations_path: str = "migrations/"
    seed_data_file: str = ""
    connection_string_template: str = ""
    backup_policy: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def table_count(self) -> int:
        return len(self.tables)

    def get_table(self, name: str) -> TableDefinition | None:
        for table in self.tables:
            if table.name == name:
                return table
        return None


# ── API Definitions ─────────────────────────────────────────────────────

class HTTPMethod(str, Enum):
    GET = "get"
    POST = "post"
    PUT = "put"
    PATCH = "patch"
    DELETE = "delete"
    HEAD = "head"
    OPTIONS = "options"


class APIEndpoint(BaseModel):
    """A single API endpoint definition."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    path: str = ""
    method: HTTPMethod = HTTPMethod.GET
    summary: str = ""
    description: str = ""
    request_body: dict[str, Any] = Field(default_factory=dict)
    response_body: dict[str, Any] = Field(default_factory=dict)
    query_parameters: list[dict[str, Any]] = Field(default_factory=list)
    path_parameters: list[dict[str, Any]] = Field(default_factory=list)
    headers: dict[str, str] = Field(default_factory=dict)
    status_codes: list[int] = Field(default_factory=lambda: [200, 400, 401, 500])
    auth_required: bool = True
    rate_limit: int = 100  # requests per minute
    cache_ttl_seconds: int | None = None
    idempotent: bool = False
    tags: list[str] = Field(default_factory=list)
    example_request: dict[str, Any] | None = None
    example_response: dict[str, Any] | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class APIDefinition(BaseModel):
    """Complete API specification for a service."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    service_name: str = ""
    base_url: str = "/api/v1"
    version: str = "1.0.0"
    endpoints: list[APIEndpoint] = Field(default_factory=list)
    auth_method: str = "jwt"  # jwt, oauth2, api_key, basic
    rate_limiting_enabled: bool = True
    cors_enabled: bool = True
    docs_url: str = "/docs"
    spec_format: str = "openapi_3.1"
    tags: list[dict[str, str]] = Field(default_factory=list)

    @property
    def endpoint_count(self) -> int:
        return len(self.endpoints)

    def group_by_tag(self) -> dict[str, list[APIEndpoint]]:
        groups: dict[str, list[APIEndpoint]] = {}
        for endpoint in self.endpoints:
            for tag in endpoint.tags:
                groups.setdefault(tag, []).append(endpoint)
        return groups


# ── UI Layout Definitions ───────────────────────────────────────────────

class ComponentType(str, Enum):
    BUTTON = "button"
    INPUT = "input"
    TABLE = "table"
    FORM = "form"
    CARD = "card"
    MODAL = "modal"
    CHART = "chart"
    NAVBAR = "navbar"
    SIDEBAR = "sidebar"
    FOOTER = "footer"
    DROPDOWN = "dropdown"
    LIST = "list"
    GRID = "grid"
    CONTAINER = "container"
    TABS = "tabs"
    ALERT = "alert"
    BADGE = "badge"
    ICON = "icon"
    AVATAR = "avatar"
    LOADING = "loading"
    PAGINATION = "pagination"
    BREADCRUMB = "breadcrumb"


class UILayout(BaseModel):
    """A page or component layout for the frontend."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = ""
    path: str = ""  # frontend route path
    component_type: ComponentType = ComponentType.CONTAINER
    children: list[UILayout] = Field(default_factory=list)
    props: dict[str, Any] = Field(default_factory=dict)
    styles: dict[str, str] = Field(default_factory=dict)
    data_source: str = ""  # API endpoint to fetch data
    auth_required: bool = False
    layout: str = "default"  # default, sidebar, centered, fullscreen
    state_management: str = "context"  # context, redux, zustand, recoil
    responsive: bool = True
    metadata: dict[str, Any] = Field(default_factory=dict)


# ── Full Architecture Design ────────────────────────────────────────────

class ArchitectureDesign(BaseModel):
    """Complete architecture design for a project."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    project_id: str = ""
    pattern: ArchitecturePattern = ArchitecturePattern.MICROSERVICES
    services: list[ServiceDefinition] = Field(default_factory=list)
    database: DatabaseSchema | None = None
    api: APIDefinition | None = None
    frontend: list[UILayout] = Field(default_factory=list)
    deployment_strategy: DeploymentStrategy = DeploymentStrategy.ROLLING
    communication_protocols: list[CommunicationProtocol] = Field(
        default_factory=lambda: [CommunicationProtocol.REST]
    )
    diagram_url: str = ""
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def service_count(self) -> int:
        return len(self.services)

    def get_service(self, name: str) -> ServiceDefinition | None:
        for service in self.services:
            if service.name == name:
                return service
        return None
