"""Deployment and cloud infrastructure models for Component 11 — Autonomous Cloud Architect.

The Cloud Architect autonomously:
- Evaluates cloud providers (AWS, Azure, GCP) for cost/latency/reliability/compliance
- Generates Terraform, Kubernetes, and Helm configurations
- Manages the full deployment lifecycle
- Monitors and auto-scales in production
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class CloudProvider(str, Enum):
    AWS = "aws"
    AZURE = "azure"
    GCP = "gcp"
    HYBRID = "hybrid"
    MULTI_CLOUD = "multi_cloud"
    ON_PREM = "on_premise"
    EDGE = "edge"


class DeploymentStatus(str, Enum):
    PENDING = "pending"
    PROVISIONING = "provisioning"
    CONFIGURING = "configuring"
    DEPLOYING = "deploying"
    HEALTH_CHECK = "health_check"
    LIVE = "live"
    FAILED = "failed"
    ROLLING_BACK = "rolling_back"
    ROLLED_BACK = "rolled_back"
    DESTROYED = "destroyed"


class ContainerRuntime(str, Enum):
    DOCKER = "docker"
    CONTAINERD = "containerd"
    CRI_O = "cri_o"
    PODMAN = "podman"


class Orchestrator(str, Enum):
    KUBERNETES = "kubernetes"
    NOMAD = "nomad"
    DOCKER_SWARM = "docker_swarm"
    ECS = "ecs"
    SELF_MANAGED = "self_managed"


class IaCTool(str, Enum):
    TERRAFORM = "terraform"
    PULUMI = "pulumi"
    CDK = "cdk"
    ANSIBLE = "ansible"
    HELM = "helm"
    CROSSPLANE = "crossplane"


class InfrastructureResource(BaseModel):
    """A single infrastructure resource to provision."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    resource_type: str = ""  # aws_ecs_service, google_container_cluster, etc.
    name: str = ""
    provider: CloudProvider = CloudProvider.AWS
    configuration: dict[str, Any] = Field(default_factory=dict)
    depends_on: list[str] = Field(default_factory=list)
    tags: dict[str, str] = Field(default_factory=dict)
    cost_estimate_monthly: float = 0.0
    region: str = "us-east-1"
    metadata: dict[str, Any] = Field(default_factory=dict)


class ServiceConfig(BaseModel):
    """Configuration for a single service in the deployment."""

    name: str = ""
    image: str = ""
    tag: str = "latest"
    replicas: int = 2
    port: int = 8000
    env_vars: dict[str, str] = Field(default_factory=dict)
    secrets: list[str] = Field(default_factory=list)
    cpu_limit: str = "500m"
    memory_limit: str = "512Mi"
    cpu_request: str = "250m"
    memory_request: str = "256Mi"
    health_check: dict[str, Any] = Field(
        default_factory=lambda: {
            "path": "/health",
            "initial_delay_seconds": 10,
            "period_seconds": 30,
        }
    )
    auto_scaling: dict[str, Any] = Field(
        default_factory=lambda: {
            "enabled": True,
            "min_replicas": 2,
            "max_replicas": 10,
            "cpu_threshold": 70,
        }
    )
    ingress_rules: list[dict[str, Any]] = Field(default_factory=list)


class InfrastructureSpec(BaseModel):
    """Complete infrastructure specification generated by the Cloud Architect."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    project_id: str = ""
    provider: CloudProvider = CloudProvider.AWS
    regions: list[str] = Field(default_factory=lambda: ["us-east-1"])
    orchestrator: Orchestrator = Orchestrator.KUBERNETES
    container_runtime: ContainerRuntime = ContainerRuntime.DOCKER
    iact_tool: IaCTool = IaCTool.TERRAFORM
    resources: list[InfrastructureResource] = Field(default_factory=list)
    services: list[ServiceConfig] = Field(default_factory=list)
    global_env_vars: dict[str, str] = Field(default_factory=dict)
    global_secrets: list[str] = Field(default_factory=list)
    domain: str = ""
    ssl_certificate_arn: str = ""
    monitoring_stack: dict[str, Any] = Field(
        default_factory=lambda: {
            "prometheus": True,
            "grafana": True,
            "alert_manager": True,
            "logging": "elasticsearch",
        }
    )
    backup_config: dict[str, Any] = Field(
        default_factory=lambda: {
            "enabled": True,
            "retention_days": 30,
            "time": "03:00 UTC",
        }
    )
    network: dict[str, Any] = Field(
        default_factory=lambda: {
            "vpc_cidr": "10.0.0.0/16",
            "public_subnets": ["10.0.1.0/24", "10.0.2.0/24"],
            "private_subnets": ["10.0.10.0/24", "10.0.11.0/24"],
        }
    )
    estimated_monthly_cost: float = 0.0
    compliance: list[str] = Field(default_factory=list)
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


class DeploymentPlan(BaseModel):
    """A complete deployment plan generated by the Cloud Architect."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    project_id: str = ""
    infrastructure: InfrastructureSpec | None = None
    status: DeploymentStatus = DeploymentStatus.PENDING
    version: str = "1.0.0"
    rollback_version: str = ""
    strategy: str = "rolling"  # rolling, blue_green, canary
    canary_percent: float = 10.0
    approved_by: str = ""  # agent or human id
    approved_at: datetime | None = None
    deployed_at: datetime | None = None
    health_endpoint: str = ""
    deployment_url: str = ""
    logs: list[dict[str, Any]] = Field(default_factory=list)
    errors: list[str] = Field(default_factory=list)
    metrics_after_deploy: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    @property
    def is_live(self) -> bool:
        return self.status == DeploymentStatus.LIVE

    @property
    def has_failed(self) -> bool:
        return self.status in (
            DeploymentStatus.FAILED,
            DeploymentStatus.ROLLED_BACK,
        )


class CloudProviderEvaluation(BaseModel):
    """Evaluation of a cloud provider for a specific project."""

    provider: CloudProvider = CloudProvider.AWS
    cost_score: float = Field(ge=0.0, le=1.0, default=0.5)
    latency_score: float = Field(ge=0.0, le=1.0, default=0.5)
    reliability_score: float = Field(ge=0.0, le=1.0, default=0.5)
    compliance_score: float = Field(ge=0.0, le=1.0, default=0.5)
    feature_fit_score: float = Field(ge=0.0, le=1.0, default=0.5)
    estimated_monthly_cost: float = 0.0
    regions_available: list[str] = Field(default_factory=list)
    compliance_certifications: list[str] = Field(default_factory=list)
    pros: list[str] = Field(default_factory=list)
    cons: list[str] = Field(default_factory=list)
    overall_score: float = Field(ge=0.0, le=1.0, default=0.5)

    @property
    def weighted_score(self) -> float:
        return (
            self.cost_score * 0.25
            + self.latency_score * 0.20
            + self.reliability_score * 0.25
            + self.compliance_score * 0.15
            + self.feature_fit_score * 0.15
        )
